apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vendere-core-fe
spec:
  rules:
    - host: vendere.store
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vendere-core-fe
                port:
                  number: 3000
