apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vendere-core-fe-ingress
  annotations:
    meta.helm.sh/release-name: vendere-core-fe
    meta.helm.sh/release-namespace: default
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-fe
  rules:
    - host: vendere.store
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vendere-core-fe-service
                port:
                  number: 80
{{/*  tls:*/}}
{{/*    - hosts:*/}}
{{/*        - vendere.store*/}}
{{/*      secretName: vendere-store-tls*/}}
