apiVersion: v2
name: vendere-core-fe
description: A Helm chart for deploying the vendere-core-fe service
version: 1.0.0
appVersion: 1.0.0

dependencies:
  - name: ingress-nginx
    version: "4.0.6"  # Specify the version of the ingress-nginx chart you wish to use
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingress-nginx.enabled