replicaCount: 1

image:
  repository: sh0n3/vendere-core-fe
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"
#
#ingress:
#  enabled: true
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
#  hosts:
#    - host: vendere.store
#      paths:
#        - path: /
#          pathType: Prefix
#          backend:
#            service:
#              name: vendere-core-fe
#              port:
#                number: 3000

controller:
  ingressClass: "my-nginx-ingress"
