name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker registry
      run: |
        echo "Logging in to Docker Hub..."
        echo "Username: ${{ secrets.DOCKER_USERNAME }}"
        echo "Password length: ${#DOCKER_PASSWORD}"
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin https://index.docker.io/v1/

    - name: Build Docker image
      run: docker build -t sh0n3l/sh0n3/vendere-core-fe:latest .

    - name: Push Docker image
      run: docker push sh0n3l/sh0n3/vendere-core-fe:latest

    - name: Configure Kubernetes context
      run: |
        kubectl config set-cluster minikube --server=http://77.237.247.251 --certificate-authority=$HOME/.minikube/ca.crt --embed-certs=true &&
        kubectl config set-credentials user --client-certificate=$HOME/.minikube/client.crt --client-key=$HOME/.minikube/client.key --embed-certs=true &&
        kubectl config set-context minikube --cluster=minikube --user=user &&
        kubectl config use-context minikube

    - name: Deploy Helm chart
      run: helm install vendere-products-fe helm/vendere-products-fe -n default --create-namespace
